### ISSUE TITLE
masci-tools/masci_tools/io/kkr_params.py

### ISSUE THREAD

**Issue by pteronura** [JuDFTteam/masci-tools#2]
'use_input_alat' should be properly defined, i.e. without <> around it

appeared in:
2020-02-03 15:47:55 [478 | REPORT]: [817|kkr_startpot_wc|start]: INFO: started VoroStart workflow version 0.10.6
2020-02-03 15:47:55 [479 | REPORT]: [817|kkr_startpot_wc|start]: INFO: use the following parameter:
use_mpi: True
Resources: {'num_machines': 1}
Walltime (s): 3600
queue name: 
scheduler command: 
description: 
label: 
dos_params: {'emax': 1, 'emin': -1, 'kmesh': [30, 30, 30], 'nepts': 61, 'tempr': 200}
Max. number of voronoi reruns: 8
factor cluster increase: 1.1
default cluster radius (in alat): 0.7212881311274263
min. number of atoms in screening cls: 60
min. dist in DOS contour to emin/emax: 1.0 eV
threshold where DOS is zero: 0.01 states/eV
minimal distance of highest core state from EMIN: 0.2 Ry

2020-02-03 15:47:57 [480 | REPORT]: [817|kkr_startpot_wc|run_voronoi]: INFO: input params: {'FCM': None, 'INS': None, 'EMAX': None, 'EMIN': None, 'GMAX': 60.0, 'ICST': None, 'IMIX': None, 'IRID': 600, 'LMAX': 3, 'NAEZ': None, 'NMIN': None, 'NPOL': None, 'NPT1': None, 'NPT2': None, 'NPT3': None, 'RMAX': 6.0, 'EFSET': None, 'FILES': None, 'IEMXD': None, 'IPAND': 100, 'KVREL': None, 'NATYP': None, 'NCHEB': None, 'NSPIN': 2, 'R_LOG': None, 'TEMPR': None, '<SITE>': None, 'BRYMIX': None, 'HFIELD': None, 'ITDBRY': None, 'JIJRAD': None, 'KEXCOR': None, 'KSHAPE': None, 'N1SEMI': None, 'N2SEMI': None, 'N3SEMI': None, 'NSHELD': None, 'NSTEPS': None, 'QBOUND': None, 'RUNOPT': ['FINDSIZE', 'MPIenerg', 'WRITEALL'], 'STRMIX': None, 'TKSEMI': None, 'VCONST': None, '<LLOYD>': None, '<SHAPE>': None, '<ZATOM>': None, 'BRAVAIS': None, 'CPAINFO': None, 'EMUSEMI': None, 'LINIPOL': None, 'NPAN_EQ': None, 'RCLUSTZ': 0.8, 'TESTOPT': None, 'XINIPOL': None, '<DELTAE>': None, '<KAOEZL>': None, '<KAOEZR>': None, '<RBASIS>': None, '<RBLEFT>': None, '<RMTREF>': None, '<SOCSCL>': None, 'BZDIVIDE': None, 'EBOTSEMI': None, 'JIJRADXY': None, 'JIJSITEI': None, 'JIJSITEJ': None, 'NAT_LDAU': None, 'NLEFTHOS': None, 'NPAN_LOG': None, 'NPOLSEMI': None, 'NRIGHTHO': None, 'RCLUSTXY': None, 'ZPERIODL': None, 'ZPERIODR': None, '<NLBASIS>': None, '<NRBASIS>': None, '<RBRIGHT>': None, '<RMTCORE>': None, '<RMTREFL>': None, '<RMTREFR>': None, '<TOLRDIF>': None, 'ALATBASIS': 22.980959400836, 'CARTESIAN': None, 'FSEMICORE': None, 'INTERFACE': None, 'KREADLDAU': None, 'LAMBDA_XC': None, 'LDAU_PARA': None, '<CPA-CONC>': None, '<FPRADIUS>': None, '<use_input_alat>': True}
2020-02-03 15:47:57 [481 | REPORT]: [817|kkr_startpot_wc|run_voronoi]: INFO: setting KSHAPE to default value 2
2020-02-03 15:47:57 [482 | REPORT]: [817|kkr_startpot_wc|run_voronoi]: INFO: setting INS to default value 1
2020-02-03 15:47:57 [483 | REPORT]: [817|kkr_startpot_wc|run_voronoi]: INFO: setting RCLUSTZ to 0.8
2020-02-03 15:47:57 [484 | REPORT]: [817|kkr_startpot_wc|run_voronoi]: INFO: setting RMAX to 6.0 (needed for DOS check with KKRcode)
2020-02-03 15:47:57 [485 | REPORT]: [817|kkr_startpot_wc|run_voronoi]: INFO: setting GMAX to 60.0 (needed for DOS check with KKRcode)
2020-02-03 15:47:58 [487 | REPORT]: [817|kkr_startpot_wc|on_except]: Traceback (most recent call last):
  File "/Users/kovacik/CODES/venv_aiida1.0.1_py3/lib/python3.7/site-packages/plumpy/process_states.py", line 220, in execute
    result = self.run_fn(*self.args, **self.kwargs)
  File "/Users/kovacik/CODES/venv_aiida1.0.1_py3/lib/python3.7/site-packages/aiida/engine/processes/workchains/workchain.py", line 181, in _do_step
    finished, stepper_result = self._stepper.step()
  File "/Users/kovacik/CODES/venv_aiida1.0.1_py3/lib/python3.7/site-packages/plumpy/workchains.py", line 283, in step
    finished, result = self._child_stepper.step()
  File "/Users/kovacik/CODES/venv_aiida1.0.1_py3/lib/python3.7/site-packages/plumpy/workchains.py", line 515, in step
    finished, result = self._child_stepper.step()
  File "/Users/kovacik/CODES/venv_aiida1.0.1_py3/lib/python3.7/site-packages/plumpy/workchains.py", line 283, in step
    finished, result = self._child_stepper.step()
  File "/Users/kovacik/CODES/venv_aiida1.0.1_py3/lib/python3.7/site-packages/plumpy/workchains.py", line 234, in step
    return True, self._fn(self._workchain)
  File "/Users/kovacik/CODES/venv_aiida1.0.1_py3/src/aiida-kkr/aiida_kkr/workflows/voro_start.py", line 393, in run_voronoi
    params = update_params_wf(self.ctx.last_params, updatenode)
  File "/Users/kovacik/CODES/venv_aiida1.0.1_py3/lib/python3.7/site-packages/aiida/engine/processes/functions.py", line 191, in decorated_function
    result, _ = run_get_node(*args, **kwargs)
  File "/Users/kovacik/CODES/venv_aiida1.0.1_py3/lib/python3.7/site-packages/aiida/engine/processes/functions.py", line 163, in run_get_node
    result = process.execute()
  File "/Users/kovacik/CODES/venv_aiida1.0.1_py3/lib/python3.7/site-packages/aiida/engine/processes/functions.py", line 374, in execute
    result = super(FunctionProcess, self).execute()
  File "/Users/kovacik/CODES/venv_aiida1.0.1_py3/lib/python3.7/site-packages/plumpy/processes.py", line 88, in func_wrapper
    return func(self, *args, **kwargs)
  File "/Users/kovacik/CODES/venv_aiida1.0.1_py3/lib/python3.7/site-packages/plumpy/processes.py", line 1065, in execute
    return self.future().result()
  File "/Users/kovacik/CODES/venv_aiida1.0.1_py3/lib/python3.7/site-packages/plumpy/futures.py", line 34, in result
    return super(Future, self).result(timeout)
  File "/Users/kovacik/CODES/venv_aiida1.0.1_py3/lib/python3.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/kovacik/CODES/venv_aiida1.0.1_py3/lib/python3.7/site-packages/plumpy/process_states.py", line 220, in execute
    result = self.run_fn(*self.args, **self.kwargs)
  File "/Users/kovacik/CODES/venv_aiida1.0.1_py3/lib/python3.7/site-packages/aiida/engine/processes/functions.py", line 422, in run
    result = self._func(*args, **kwargs)
  File "/Users/kovacik/CODES/venv_aiida1.0.1_py3/src/aiida-kkr/aiida_kkr/tools/common_workfunctions.py", line 60, in update_params_wf
    nodedesc=nodedesc, **updatenode_dict)
  File "/Users/kovacik/CODES/venv_aiida1.0.1_py3/src/aiida-kkr/aiida_kkr/tools/common_workfunctions.py", line 105, in update_params
    raise InputValidationError('unvalid key "{}" in input parameter node'.format(key))
aiida.common.exceptions.InputValidationError: unvalid key "<use_input_alat>" in input parameter node

**Comment by PhilippRue** [comment]
Fixed with commits
* bdd83b11122da7312a7facef28402381ef9b57d4
* 1cccc39fcd124e483485dacd10d691b5dd6b5ccf
* 42c2e7dde70b1e0d37686d112e95c278720371e0

Now this works:
```
k = kkrparams()
k.set_multiple_values(ALATBASIS=4.5, use_input_alat=True)
```

which gave an invalid key error before. The error raised in 
https://github.com/JuDFTteam/aiida-kkr/blob/9589e2e13ca5a018f97fd6c79251765e57a553b2/aiida_kkr/tools/common_workfunctions.py#L105
should not reappear with this change now since the keywork `use_input_alat ` will be properly detected to be in the `_ignored_keys` list defined in 
https://github.com/JuDFTteam/aiida-kkr/blob/9589e2e13ca5a018f97fd6c79251765e57a553b2/aiida_kkr/tools/common_workfunctions.py#L22
